steps:
- id: 'build'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      cd api
      docker build -t build-api .
      # sharing docker socket is needed for testcontainers execution (otherwise, tests would fail)
      docker run -v /var/run/docker.sock:/var/run/docker.sock -v /workspace:/output build-api
      ls -al /workspace/

- id: 'pull-cache'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "$_GCLOUD_SERVICE_ACCOUNT_CONTENT" | base64 --decode > /workspace/pokeraiders.json
      more /workspace/pokeraiders.json
      gcloud auth activate-service-account --key-file=/workspace/pokeraiders.json
      export BUCKET_PATH=gs://$_BUCKET/pokeraiders-api-$(date '+%Y%m%dT%H%M').$_ENV.jar
      echo $BUCKET_PATH
      ls -al /workspace/
      gsutil cp /workspace/pokeraiders-api.jar "$BUCKET_PATH"
      cd api/
      gcloud compute instances create pokeraiders-$_ENV \
          --image-family debian-10 \
          --image-project debian-cloud \
          --machine-type g1-small \
          --scopes "userinfo-email,cloud-platform" \
          --metadata-from-file startup-script=instance-startup.sh \
          --metadata BUCKET=$_BUCKET,RECAPTCHA_SECRET=$_RECAPTCHA_SECRET,DATASOURCE_URL=$_DATASOURCE_URL,PG_USER=$_PG_USER,PG_PASSWORD=$_PG_PASSWORD,BUCKET_PATH=$BUCKET_PATH \
          --zone $_ZONE \
          --tags http-server

tags: ['deploy', '$_ENV']
logsBucket: 'gs://$_BUCKET/logs'
substitutions:
  _BUCKET: pokeraiders
  _ZONE: europe-west1-c
  # _RECAPTCHA_SECRET: ...
  # _DATASOURCE_URL: ...
  # _PG_USER: ...
  # _PG_PASSWORD: ...
  # _GCLOUD_SERVICE_ACCOUNT_CONTENT: ...
  # _ENV: prod | stg | ...
